BLOCKBUSTER/Votaciones/Proyecto_nube/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
]

BLOCKBUSTER/Votaciones/app/urls.py
	
from django.urls import path 
from . import views 
 
app_name = 'app' 
urlpatterns = [
    path('', views.index, name='index'),
    path('categorias/', views.categorias_view, name= 'categorias'), 
    path('categoria/<int:id>', views.categoria_view, name= 'categoria'), 
    path('peliculas/', views.peliculas_view, name= 'peliculas'), 
    path('acerca/', views.acerca_view, name='acerca'),
    
    #formulario para categoria
    path('categorias/crear/', views.form_crear_categoria_view, name='form_crear_categoria_view'),
    path('categorias/crear_post/', views.crear_categoria_post, name='crear_categoria_post'),
]

BLOCKBUSTER/Votaciones/app/models.py
from django.db import models

# Create your models here.


class Categoria(models.Model):
    nombre = models.CharField(max_length=200, null=False)
    descripcion = models.TextField(null=True) 
 
    def __str__(self):
        return self.nombre
 
    class Meta:
        app_label = 'app'

        	
class Pelicula(models.Model):
    nombre = models.CharField(max_length=200, null=False)
    year = models.IntegerField(null=True)
    descripcion = models.TextField(null=True)
    categoria = models.ForeignKey(Categoria,
                  related_name='peliculas',
                  null=False,                  
                  on_delete=models.PROTECT)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
 
    def __str__(self):
        return self.titulo
        
    class Meta:
        app_label = 'app'

BLOCKBUSTER/Votaciones/app/views.py
from pickle import TRUE
import re
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Categoria, Pelicula
 
def index(request):
    return HttpResponse("Hola, mundo")

def categorias_view(request):
    #obtiene toda las categoras
    lista = Categoria.objects.all()
    #crear contexto
    contexto= {
        'categorias': lista
    }
        
    return render(request, 'app/categorias.html', contexto)

def categoria_view(request, id):

    contexto = {
        'actor': 'Tom Hanks',
        'edad': '64',
        'esJubilado':False,
        'filmografia': [
            {'Titulo': 'Naufrago', 'year': 2000},
            {'Titulo': 'Forrest Gump', 'year': 1994},
            {'Titulo': 'Codigo DaVinci', 'year': 2006},
            {'Titulo': 'toy Story', 'year': 1995},
        ]
    }
    return render(request, 'app/categoria.html', contexto)

def form_crear_categoria_view(request):
    return render(request, 'app/crearCategoria.html')

def crear_categoria_post(request):
    nombre = request.POST['nombre']
    descripcion = request.POST['descripcion']

    c = Categoria()
    c.nombre = nombre
    c.descripcion = descripcion

    c.save()

    return redirect('app:categorias')

def peliculas_view(request):
    return render(request, "app/peliculas.html")

def acerca_view(request):
    return render(request, 'app/acerca.html')

BLOCKBUSTER/Votaciones/app/templates/app/acerca.html
{% extends "app/base.html" %}
{% block titulo %}
acerca de
{% endblock %}

{% block contenido %}
<h1>Ingenieros</h1>
<ul>
    <li>diego diaz</li>
</ul>
{% endblock %}

<!-- hola soy hjohn -->

BLOCKBUSTER/Votaciones/app/templates/app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Categorias</title>
    <link rel="stylesheet" href="{% static 'app/css/estilo.css' %}">
</head>
<body>
    <div class ="contenedor">
        <header>
            <div class="logo" >
                BLOCKBUSTER
            </div>
            <div class="titulo">
                {% block titulo %}
                {% endblock %}
            </div>
        </header>
        <nav class="navegacion">
            <ul>
                <li><a href="{% url 'app:peliculas' %}">Peliculas</a></li>
                <li> <a href="{% url 'app:categorias' %}">Categorias</a></li>
                <li> <a href="{% url 'app:acerca' %}">acerca</a></li>
                <li><a href="#">salir</a></li>
            </ul>
        </nav>

        <main>
            {% block contenido %}
            {% endblock %}
        </main>
    </div>

    
    
</body>
</html>

BLOCKBUSTER/Votaciones/app/templates/app/categoria.html
{% extends "app/base.html" %}

{% block titulo %}
categoria
{% endblock %}

{% block contenido %}
<a href="{% url 'app:peliculas' %}">Ir a la pagina peliculas</a>
    <br>
    <a href="{% url 'app:index' %}">Ir a inicio</a>
    <br>

    <h1>Categoria</h1>
    <p>El nombre del actor es: {{actor}} y tiene {{edad}}</p>

    {% if esJubilado %}
    <p>El actor es jubilado</p>

    {% else %}
    <p>El actor trabaja activamente en el cine</p>
    {% endif %}
    
    <h2> Filmografia del actor</h2>

    <ul>
        {% for pelicula in filmografia %}
        <li>{{ pelicula.Titulo}}</li>
        {% endfor %}
    </ul>
    <hr>
    <h2> Tabla De pelicuals del actor</h2>
    <table border="1">
        <thead>
            <tr>
                <th>Titulo</th>
                <th>Año</th>
            </tr>
        </thead>
        <tbody>
            {% for movie in filmografia %}
            <tr>
                <td>{{ movie.Titulo }}</td>
                <td>{{ movie.year }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

BLOCKBUSTER/Votaciones/app/templates/app/categorias.html
{% extends "app/base.html" %}

{% block titulo %}
categorias
{% endblock %}

{% block contenido %}
<a href="{% url 'app:form_crear_categoria_view' %}">Crear Categoria</a>
<ul>
    {% for c in categorias %}
    <li>{{ c.nombre }}</li>
    
    {% endfor %}
</ul>

{% endblock %}

BLOCKBUSTER/Votaciones/app/templates/app/crearCategoria.html
{% extends "app/base.html" %}

{% block titulo %}
categorias
{% endblock %}

{% block contenido %}
<h3>Datos De la categoria</h3>
<hr>

<form action="{% url 'app:crear_categoria_post' %}" method="post">
    {% csrf_token %}
    <fieldset>
        <label>Nombre</label>
        <input type="text" name="nombre">
    </fieldset>

    <fieldset>
        <label>Descripcion</label>
        <input type="text" name="descripcion">
    </fieldset>
    <fieldset>
        <button type="submit">Crear Categoria</button>
    </fieldset>

</form>
{% endblock %}

BLOCKBUSTER/Votaciones/app/templates/app/peliculas.html
{% extends "app/base.html" %}

{% block titulo %}
Peliculas
{% endblock %}

{% block contenido %}
<table border="1">
    <theard>
        <tr>
            <th>Titulo</th>
            <th>Año</th>
            <th>Categoria</th>
        </tr>
    </theard>
    <tbody>
        <tr>
            <td>wall_e</td>
            <td>2005</td>
            <td>Infantil</td>
        </tr>
        <tr>
            <td>Soul</td>
            <td>2020</td>
            <td>Infantil</td>
        </tr>
        <tr>
            <td>Duro de matar</td>
            <td>1987</td>
            <td>Accion</td>
        </tr>
        <tr>
            <td>Pretty Woman</td>
            <td>1997</td>
            <td>Romance</td>
        </tr>
    </tbody>
</table>
{% endblock %}