proyectonube2/Votaciones/Proyecto_nube/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
]

proyectonube2/Votaciones/app/urls.py
	
from django.urls import path 
from . import views 
 
app_name = 'app' 
urlpatterns = [
    path('', views.index, name='index'),

    path('login/', views.login_view, name='login'),
    path('entrar/', views.entrar, name='entrar'),
    path('decano/', views.decano_view, name='decano'),
    path('estudiante/', views.estudiante_view, name='estudiante'),

    path('crearEstudiante/', views.crearEstudiante_view, name='crearEstudiante'),
    path('crearEstudiante_crear/', views.form_crearEstudiante_view, name='form_crearEstudiante_view'),
    path('crearEstudiante_post/', views.crearEstudiante_post, name='crearEstudiante_post'),
    path('listadoEstudiantes/', views.listadoEstudiantes_view, name='listadoEstudiantes'),
    
    
    path('crearVotacion_crear/', views.form_crearVotacion_view, name='form_crearVotacion_view'),
    path('crearVotacion_post/', views.crearVotacion_post, name='crearVotacion_post'),

    path('crearVotacion/', views.crearVotacion_view, name='crearVotacion'),
    path('listadoVotaciones/', views.listadoVotaciones_view, name='listadoVotaciones'),




    
    path('consultlaVotacionesRepre/', views.consultlaVotacionesRepre_view, name='consultlaVotacionesRepre'),
    path('postularCandidato/', views.postularCandidato_view, name='postularCandidato'),
    path('consultarVotacionE/', views.consultarVotacionE_view, name='consultarVotacionE'),
    path('votar_repre_fa/', views.votar_repre_fa_view, name='votar_repre_fa'),
    path('votar_repre_se/', views.votar_repre_se_view, name='votar_repre_se'),
    path('listadodevotaciones/', views.listadodevotaciones_view, name='listadodevotaciones'),
    path('consultarvotacion/', views.consultarvotacion_view, name='consultarvotacion'),
    path('postularse/', views.postularse_view, name='postularse'),
    path('consultavoto/', views.consultavoto_view, name='consultavoto'),
]

proyectonube2/Votaciones/app/templates/app/base2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block css %}
    {% endblock %}
    <title>Login</title>

</head>
<body>
    <div class ="contenedor">
        <header>
            <div class="logo" >
                <div class="logo">
                    <img class="imagen" src="{% static 'app/img/logos.png' %}" alt="logosantoto">
                </div>
            </div>
        </header>
        <nav class="navegacion">
            {% block login %}
            {% endblock %}
        </nav>

        <main>
            {% block contenido %}
            {% endblock %}
        </main>
    </div> 
</body>
</html>

proyectonube2/Votaciones/app/templates/app/base3.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block pestaña %}
    {% endblock %}
    <title>Decano</title>

    {% block css %}
    {% endblock %}

</head>
<body>
    <div class ="contenedor">
        <header>
            <div class="titulo">
                {% block titulo %}
                {% endblock %}
            </div>
        </header>
        {% block menu %}
        {% endblock %}
        <div class="contenido">
            {% block contenido %}
            {% endblock %}
        </div>
        <div class="footer">
        </div>
    </div> 
</body>
</html>

proyectonube2/Votaciones/app/templates/app/consultarVotacionE.html
{% extends "app/base3.html" %}
{% load static %}

{% block pestaña %}
<title>Decano: Consulta Votacion Estudiante</title>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'app/css/consultarVotacionE.css' %}">
{% endblock %}

{% block titulo %}
<i><a href="{% url 'app:login' %}"><img id="logout" src="{% static 'app/img/logout.jpg' %}" alt="logo" class="logout"></a></a></i>

<img id="logo" src="{% static 'app/img/logos.png' %}" alt="logo" class="logosantoto"></a>
{% endblock %}

{% block menu %}       
<nav class="menu">
    <ul>
        <h2>Menu</h2>
        <br>
        <li><a href="{% url 'app:crearEstudiante' %}">Crear Estudiante</a></li>
        <li><a href="{% url 'app:listadoEstudiantes' %}">Lista de Estudiantes</a></li>
        <li><a href="{% url 'app:crearVotacion' %}">Creacion Votacion</a></li>
        <li><a href="{% url 'app:listadoVotaciones' %}">Listado De Votacion</a></li>
        <li><a href="{% url 'app:decano' %}">Volver a Menu Decano</a></li>
    </ul>
</nav>
{% endblock %}

{% block contenido %}
<div class="datosdelestudiante">
    <form action="" >
        <div class="titulo1">
            <h2>Consultar votación Estudiante</h2>
        </div>
        <div class="formulario1">                      
          <div class="flex">
              <label for="">Nombre Votacion</label>
              <input type="text" >
          </div>
          <div class="flex">
              <label for="">Fecha de Inicio</label>
              <input type="text"  >
          </div>
          <div class="flex">
              <label for="">Fecha De Finalizacion</label>
              <input type="text" >
          </div>

          <div class="flex">
              <label for="">Ciclo</label>
              <input type="text" > 
          </div>

          <div class="flex">
              <label for="">Estado Actual De La Votacion</label>
              <input type="text" >
          </div>
          <div class="flex">
              <label for="">Total De Estudiantes Habilitados Para Votar</label>
              <input type="text" >
          </div>
          <div class="flex">
              <label for="">Estudiantes Que Han Votado</label>
              <input type="text" >
          </div>
          <div class="flex">
              <label for="">Porcentaje De Votacion</label>
              <input type="text" >
          </div>
        </div>
        <div class="titulo2">
            <h3>Crear Estudiante</h3>
        </div>                      
      <table class="tabla1">
          <tr>
              <th>Nombre y Apellido<input type="text" required></th>
              <th>N° de Votos<input type="text" required></th>
              <th>Semestre<input type="text" required></th>
          </tr>
      </table>

      <div class="botones">
          <a href="{% url 'app:postularCandidato' %}" class="boton">Agregar Candidato</a>
     </div>            
    </form>
</div>
{% endblock %} 

proyectonube2/Votaciones/app/templates/app/consultarvotacion.html
{% extends "app/base3.html" %}
{% load static %}

{% block pestaña %}
<title>Estudiante: Consulta Votacion De Semestre</title>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'app/css/consultarvotacion.css' %}">
{% endblock %}

{% block titulo %}
<i><a href="{% url 'app:login' %}"><img id="logout" src="{% static 'app/img/logout.jpg' %}" alt="logo" class="logout"></a></a></i>

<img id="logo" src="{% static 'app/img/logos.png' %}" alt="logo" class="logosantoto"></a>

{% endblock %}


{% block menu %}     
<nav class="menu">
    <h1>Menu</h1>
    <ul> 
        <li><a href="{% url 'app:votar_repre_fa' %}">Votar por representante de facultad </a></li>
        <li><a href="{% url 'app:votar_repre_se' %}">Votar por representante de semestre</a></li>
        <li><a href="{% url 'app:listadodevotaciones' %}">Listado de votaciones</a></li>
        <li><a href="{% url 'app:estudiante' %}">Volver Menu Estudiante</a></li>
      </ul>
  </nav>
{% endblock %}

{% block contenido %}
<label value="represemestre" ></label>

            <br>
            <label>Fecha de inicio:</label>

            <br>
            <label>Fecha de finalizacion:</label>

            <br>
            <label>Ciclo:</label>

            <h2>Candidatos</h2>
            <table>
                <tr>
                    <td><strong>Nombres y apellidos</strong></td>
                    
                    <td><strong>N° de votos</strong></td>
                </tr>

                <tr>
                    <td>Pepito Pinilla Ramires</td>
                    <td>Aun no Disponible</td>
                </tr>

                <tr>
                    <td>Juana Marillo Robledo</td>
                    <td>Aun no Disponible</td>
                </tr>
                <br>
            </table>
            <a class="postularse" href="{% url 'app:postularse' %}">postularse</a> 
            <a class="consultar" href="{% url 'app:consultavoto' %}">consultar mi voto</a>
{% endblock %}

proyectonube2/Votaciones/app/templates/app/consultlaVotacionesRepre.html
{% extends "app/base3.html" %}
{% load static %}

{% block pestaña %}
<title>Decano: Consulta Votacion Repre</title>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'app/css/consultarVotacionesRepre.css' %}">
{% endblock %}

{% block titulo %}
<i><a href="{% url 'app:login' %}"><img id="logout" src="{% static 'app/img/logout.jpg' %}" alt="logo" class="logout"></a></a></i>

<img id="logo" src="{% static 'app/img/logos.png' %}" alt="logo" class="logosantoto"></a>
{% endblock %}

{% block menu %}       
<nav class="menu">
    <ul>
        <h2>Menu</h2>
        <br>
        <li><a href="{% url 'app:crearEstudiante' %}">Crear Estudiante</a></li>
        <li><a href="{% url 'app:listadoEstudiantes' %}">Lista de Estudiantes</a></li>
        <li><a href="{% url 'app:crearVotacion' %}">Creacion Votacion</a></li>
        <li><a href="{% url 'app:listadoVotaciones' %}">Listado De Votacion</a></li>
        <li><a href="{% url 'app:decano' %}">Volver a Menu Decano</a></li>
    </ul>
</nav>
{% endblock %}

{% block contenido %}
<div class="datosdelestudiante">
    <form action="" >
        <div class="titulo1">
            <h2>Consultar votación repre de facultad</h2>
        </div>
        <div class="formulario1">                      
          <div class="flex">
              <label for="">Nombre Votacion</label>
              <input type="text" >
          </div>
          <div class="flex">
              <label for="">Fecha de Inicio</label>
              <input type="text"  >
          </div>
          <div class="flex">
              <label for="">Fecha De Finalizacion</label>
              <input type="text" >
          </div>

          <div class="flex">
              <label for="">Ciclo</label>
              <input type="text" > 
          </div>

          <div class="flex">
              <label for="">Estado Actual De La Votacion</label>
              <input type="text" >
          </div>
          <div class="flex">
              <label for="">Total De Estudiantes Habilitados Para Votar</label>
              <input type="text" >
          </div>
          <div class="flex">
              <label for="">Estudiantes Que Han Votado</label>
              <input type="text" >
          </div>
          <div class="flex">
              <label for="">Porcentaje De Votacion</label>
              <input type="text" >
          </div>
        </div>
        <div class="titulo2">
            <h3>Crear Estudiante</h3>
        </div>                      
      <table class="tabla1">
          <tr>
              <th>Nombre y Apellido<input type="text" required></th>
              <th>N° de Votos<input type="text" required></th>
              <th>Semestre<input type="text" required></th>
          </tr>
      </table>

      <div class="botones">
          <a href="{% url 'app:postularCandidato' %}" class="boton">Agregar Candidato</a>
     </div>            
    </form>
</div>
{% endblock %} 

proyectonube2/Votaciones/app/templates/app/crearVotacion.html
{% extends "app/base3.html" %}
{% load static %}

{% block pestaña %}
<title>Decano: Crear Votacion</title>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'app/css/estiloCrearVotacion.css' %}">
{% endblock %}

{% block titulo %}
<i><a href="{% url 'app:login' %}"><img id="logout" src="{% static 'app/img/logout.jpg' %}" alt="logo"
            class="logout"></a></a></i>

<img id="logo" src="{% static 'app/img/logos.png' %}" alt="logo" class="logosantoto"></a>
{% endblock %}

{% block menu %}
<nav class="menu">
    <ul>
        <h2>Menu</h2>
        <br>
        <li><a href="{% url 'app:crearEstudiante' %}">Crear Estudiante</a></li>
        <li><a href="{% url 'app:listadoEstudiantes' %}">Lista de Estudiantes</a></li>
        <li><a href="{% url 'app:crearVotacion' %}">Creacion Votacion</a></li>
        <li><a href="{% url 'app:listadoVotaciones' %}">Listado De Votacion</a></li>
        <li><a href="{% url 'app:decano' %}">Volver a Menu Decano</a></li>
    </ul>
</nav>
{% endblock %}

{% block contenido %}
<div class="datosdelestudiante">
    <form action="{% url 'app:crearVotacion_post' %}" method="POST">

        {% csrf_token %}
        <div class="titulo1">
            <h1>Crear Votacion</h1>
        </div>
        <div class="formulario1">
            <div class="flex">
                <label for="">Nombre De Votacion</label>
                <input type="text" name="nombreVotacion" required>
            </div>
            <div class="flex">
                <label for="">Fecha de Inicio</label>
                <input type="date" name="fechaInicio" required>
            </div>
            <div class="flex">
                <label for="">Fecha De Finalizacion</label>
                <input type="date" name="fechaFinalizacion" required>
            </div>

            <div class="flex">
                <label for="">Ciclo</label>
                <input type="text" name="ciclo" required>
            </div>

            <div class="flex">
                <label for="">Elige el Tipo De Votacion</label>
 
                <select class="opciones" name="estado" >
                    <option value="">Tipo</option>
                    {% for c in TipoVotacion %}
                    <option value="{{c.id}}">{{c.nombre}}</option>
                    {% endfor %}
                    
                </select>
                
            </div>
            <br>
            <input class="enviar" type="submit">
        </div>
    </form>
</div>
{% endblock %}

proyectonube2/Votaciones/app/templates/app/decano.html
{% extends "app/base3.html" %}
{% load static %}

{% block pestaña %}
<title>Decano Menu</title>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'app/css/estiloDecano.css' %}">
{% endblock %}

{% block titulo %}
<h1>Decano (name)</h1>
<i><a href="{% url 'app:login' %}"><img id="logout" src="{% static 'app/img/logout.jpg' %}" alt="logo" class="logout"></a></a></i>
{% endblock %}


{% block menu %}     
<nav class="menu">
    <ul>
        <h2>Menu</h2>
        <br>
        <li><a href="{% url 'app:crearEstudiante' %}">Crear Estudiante</a></li>
        <li><a href="{% url 'app:listadoEstudiantes' %}">Lista de Estudiantes</a></li>
        <li><a href="{% url 'app:crearVotacion' %}">Creacion Votacion</a></li>
        <li><a href="{% url 'app:listadoVotaciones' %}">Listado De Votacion</a></li>
    </ul>
</nav>
{% endblock %}

{% block contenido %}
<img id="logo" src="{% static 'app/img/logos.png' %}" alt="logo" class="logosantoto"></a>
{% endblock %}

proyectonube2/Votaciones/app/templates/app/estudiante.html
{% extends "app/base3.html" %}
{% load static %}

{% block pestaña %}
<title>Estudiante Menu</title>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'app/css/estudiantemenu.css' %}">
{% endblock %}

{% block titulo %}
<h1>Estudiante: (name)</h1>
<i><a href="{% url 'app:login' %}"><img id="logout" src="{% static 'app/img/logout.jpg' %}" alt="logo" class="logout"></a></a></i>
{% endblock %}


{% block menu %}     
<nav class="menu">
    <ul>
        <h2>Menu</h2>
        <br>
        <li><a href="{% url 'app:votar_repre_fa' %}">Votar por representante de facultad </a></li>
        <li><a href="{% url 'app:votar_repre_se' %}">Votar por representante de semestre</a></li>
        <li><a href="{% url 'app:listadodevotaciones' %}">Listado de votaciones</a></li>
    </ul>
</nav>
{% endblock %}

{% block contenido %}
<img id="logo" src="{% static 'app/img/logos.png' %}" alt="logo" class="logosantoto"></a>
{% endblock %}

proyectonube2/Votaciones/app/templates/app/listadoEstudiantes.html
{% extends "app/base3.html" %}
{% load static %}

{% block pestaña %}
<title>Decano: Listado De Estudiantes</title>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'app/css/estiloListadoEstudiantes.css' %}">
{% endblock %}

{% block titulo %}
<i><a href="{% url 'app:login' %}"><img id="logout" src="{% static 'app/img/logout.jpg' %}" alt="logo" class="logout"></a></a></i>

<img id="logo" src="{% static 'app/img/logos.png' %}" alt="logo" class="logosantoto"></a>
{% endblock %}

{% block menu %}       
<nav class="menu">
    <ul>
        <h2>Menu</h2>
        <br>
        <li><a href="{% url 'app:crearEstudiante' %}">Crear Estudiante</a></li>
        <li><a href="{% url 'app:listadoEstudiantes' %}">Lista de Estudiantes</a></li>
        <li><a href="{% url 'app:crearVotacion' %}">Creacion Votacion</a></li>
        <li><a href="{% url 'app:listadoVotaciones' %}">Listado De Votacion</a></li>
        <li><a href="{% url 'app:decano' %}">Volver a Menu Decano</a></li>
    </ul>
</nav>
{% endblock %}

{% block contenido %}
<div class="titulo1">
    <h1>Listado De Estudiantes</h1>              
</div>
<div>
    <table class="tabla1">
        <tr>
            <th>Nombre</th>
            <th>Apellido</th>
            <th>Email</th>
            <th>Documento</th>
        </tr>
        
        {% for e in lista %}
        <tr>
            <td>{{e.user.first_name}} </td>
            <td>{{e.user.last_name}} </td>
            <td>{{e.user.email}} </td>
            <td>{{e.documento}} </td>
          </tr>
        {% endfor %}

    </table>
</div>
{% endblock %} 

proyectonube2/Votaciones/app/templates/app/listadoVotaciones.html
{% extends "app/base3.html" %}
{% load static %}

{% block pestaña %}
<title>Decano: Listado De Votos</title>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'app/css/listadoVotaciones.css' %}">
{% endblock %}

{% block titulo %}
<i><a href="{% url 'app:login' %}"><img id="logout" src="{% static 'app/img/logout.jpg' %}" alt="logo" class="logout"></a></a></i>

<img id="logo" src="{% static 'app/img/logos.png' %}" alt="logo" class="logosantoto"></a>
{% endblock %}

{% block menu %}       
<nav class="menu">
    <ul>
        <h2>Menu</h2>
        <br>
        <li><a href="{% url 'app:crearEstudiante' %}">Crear Estudiante</a></li>
        <li><a href="{% url 'app:listadoEstudiantes' %}">Lista de Estudiantes</a></li>
        <li><a href="{% url 'app:crearVotacion' %}">Creacion Votacion</a></li>
        <li><a href="{% url 'app:listadoVotaciones' %}">Listado De Votacion</a></li>
        <li><a href="{% url 'app:decano' %}">Volver a Menu Decano</a></li>
    </ul>
</nav>
{% endblock %}

{% block contenido %}
<div class="titulo1">
    <h1>Listado de Votacion</h1>
</div>
  <table class="tabla1">
      <tr>
          <th>Nombre De Votacion</th>
          <th>Ciclo</th>
          <th>Fecha De Inicio</th>
          <th>Fecha De Finalizacion</th>
          <th>Tipo De Votacion</th>
          <th>Estado De Votacion</th>
      </tr>

      {% for e in Votacion %}
      <tr>
          <td class="consultaVoto"><li><a href="{% url 'app:consultlaVotacionesRepre' %}"> Estudiante 1</a></li></td>

          <td></td>
          <td></td>
          <td></td>
          <td>Facultad</td>
          <td><div class="flex">
              <br>    
            <label for="">Elige el estado de Votacion</label>
            <select class="opciones" required>
                <option value="">Tipo</option>
                <option value="1">Activo</option>
                <option value="1">Inactivo</option>
                <option value="3">Finalizar</option>
            </select>
        </div></td>
      </tr>

      <tr>
          <td class="consultaVoto"><li><a href="{% url 'app:consultarVotacionE' %}">{{e.nombre}}</a></li></td>
          <td></td>
          <td>{{e.fechaInicio}}</td>
          <td>{{e.fechaFinal}}</td>
          <td>{{e.tipo_id}}</td>

          <td><div class="flex">
              <br>
            <label for="">Elige el estado de Votacion</label>
            <select class="opciones" required>
                <option value="">Tipo</option>
                <option value="1">Activo</option>
                <option value="1">Inactivo</option>
                <option value="3">Finalizar</option>
            </select>
        </div></td>
      </tr>
      {% endfor %}
  </table>
{% endblock %} 

proyectonube2/Votaciones/app/templates/app/listadodevotaciones.html
{% extends "app/base3.html" %}
{% load static %}

{% block pestaña %}
<title>Estudiante: Lista De Votaciones</title>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'app/css/listadodevotaciones.css' %}">
{% endblock %}

{% block titulo %}
<i><a href="{% url 'app:login' %}"><img id="logout" src="{% static 'app/img/logout.jpg' %}" alt="logo" class="logout"></a></a></i>

<img id="logo" src="{% static 'app/img/logos.png' %}" alt="logo" class="logosantoto"></a>

{% endblock %}


{% block menu %}     
<nav class="menu">
    <h1>Menu</h1>
    <ul> 
      <li><a href="{% url 'app:votar_repre_fa' %}">Votar por representante de facultad </a></li>
      <li><a href="{% url 'app:votar_repre_se' %}">Votar por representante de semestre</a></li>
      <li><a href="{% url 'app:listadodevotaciones' %}">Listado de votaciones</a></li>
      <li><a href="{% url 'app:estudiante' %}">Volver Menu Estudiante</a></li>
    </ul>
  </nav>
{% endblock %}

{% block contenido %}
<h2>Lista de votaciones</h2>
            <table id="tabla">
                <tr>
                    <td><strong>Nombres de votacion</strong></td>
                    <td><strong>Ciclo</strong></td>
                    <td><strong>Fecha de inicio</strong></td>
                    <td><strong>Fecha de finalizacion</strong></td>
                    <td><strong>Tipo de votacion </strong></td>
                </tr>
                <tr>
                    <td>
                        <li><a href="{% url 'app:consultarvotacion' %}">consultar votacion semestre</a></li>
                    </td>
                    <td>2021-2</td>
                    <td>1/02/2021</td>
                    <td>2/02/2021</td>
                    <td>Representante facultad</td>
                </tr> 
                <tr>
                    <td>
                        <li><a href="{% url 'app:consultarvotacion' %}">semestre</a></li>
                    </td>
                    <td id="ciclo">2021-2</td>
                    <td id="fechainicio">1/02/2021</td>
                    <td id="fechafin">2/02/2021</td>
                    <td id="represemestre">Representante de semestre</td>
                </tr>
                <br>
            </table>
{% endblock %}

proyectonube2/Votaciones/app/templates/app/login.html
{% extends "app/base2.html" %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'app/css/estiloLogin.css' %}">
{% endblock %}


{% block login %}
<div class="login">
    <form>
      <!-- nombre de usuario -->
      <label class="nombre" for="username">Email</label>
      <br>
      <input class="caja" type="text" placeholder="Digite Email" required/>
      <br>
      <!-- contraseña -->
      <label class="nombre" for="password">Contraseña(Documento)</label>
      <br>
      <input class="caja" type="password" placeholder="Contraseña" required/>
        <div class="botones">
            <a href="#" target="_blank" class="boton">Login</a>
            <a href="{% url 'app:decano' %}" class="boton" >Decano</a>
            <a href="{% url 'app:estudiante' %}" class="boton">Estudiante</a>
            
       </div> 
       <button type="submit">Ingresar</button>
    </form>
  </div>
{% endblock %}

proyectonube2/Votaciones/app/templates/app/postularCandidato.html
{% extends "app/base3.html" %}
{% load static %}

{% block pestaña %}
<title>Decano: Postular Candidato</title>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'app/css/postularCandidato.css' %}">
{% endblock %}

{% block titulo %}
<i><a href="{% url 'app:login' %}"><img id="logout" src="{% static 'app/img/logout.jpg' %}" alt="logo" class="logout"></a></a></i>

<img id="logo" src="{% static 'app/img/logos.png' %}" alt="logo" class="logosantoto"></a>
{% endblock %}

{% block menu %}       
<nav class="menu">
    <ul>
        <h2>Menu</h2>
        <br>
        <li><a href="{% url 'app:crearEstudiante' %}">Crear Estudiante</a></li>
        <li><a href="{% url 'app:listadoEstudiantes' %}">Lista de Estudiantes</a></li>
        <li><a href="{% url 'app:crearVotacion' %}">Creacion Votacion</a></li>
        <li><a href="{% url 'app:listadoVotaciones' %}">Listado De Votacion</a></li>
        <li><a href="{% url 'app:decano' %}">Volver a Menu Decano</a></li>
    </ul>
</nav>
{% endblock %}

{% block contenido %}
<div class="datosdelestudiante">
    <form action="" >
        <div class="titulo1">
            <h1>Postulacio De Estudiante</h1>
        </div>
        <div class="formulario1">
          <div class="flex">
              <label for="">Votacion</label>
              <input type="text" >
          </div>
          <div class="flex">
              <label for="">Estudiante</label>
              <input type="text" >
          </div>
        </div>
      <div class="botones">
          <a href="{% url 'app:decano' %}" class="boton">Agregar Candidato</a>
     </div>            
    </form>
</div>
{% endblock %}

proyectonube2/Votaciones/app/templates/app/votar_repre_se.html
{% extends "app/base3.html" %}
{% load static %}

{% block pestaña %}
<title>Estudiante: Votar por representante de semestre</title>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'app/css/votar_repre_fa.css' %}">
{% endblock %}

{% block titulo %}
<i><a href="{% url 'app:login' %}"><img id="logout" src="{% static 'app/img/logout.jpg' %}" alt="logo" class="logout"></a></a></i>

<img id="logo" src="{% static 'app/img/logos.png' %}" alt="logo" class="logosantoto"></a>

{% endblock %}


{% block menu %}     
<nav class="menu">
    <h1>Menu</h1>
    <ul> 
      <li><a href="{% url 'app:votar_repre_fa' %}">Votar por representante de facultad </a></li>
      <li><a href="{% url 'app:votar_repre_se' %}">Votar por representante de semestre</a></li>
      <li><a href="{% url 'app:listadodevotaciones' %}">Listado de votaciones</a></li>
      <li><a href="{% url 'app:estudiante' %}">Volver Menu Estudiante</a></li>
    </ul>
  </nav>
{% endblock %}

{% block contenido %}
<h2>Representante de Semestre</h2>
      <form>
        <label>Nombre de votacion: </label>

        <br>
        <label>Fecha de inicio: </label>

        <br>
        <label>Fecha de finalizacion: </label>

        <h3>Estudiantes postulados</h3>
        <table>
          <tr>
            <td><strong>Nombres y apellidos</strong></td>
            <td><strong>Propuestas</strong></td>
          </tr>

          <tr>
            <td id="candidato1">Pepito Pinilla Ramires</td>
            <td >Hacer una psicina</td>
          </tr>

          <tr>
            <td id="candidato2">Juana Marillo Robledo</td>
            <td>no mas clases</td>
          </tr>
          <br>
        </table>
        <select name="candidatos" id="candidatos">
          <optgroup label="votar">
            <option value="votar por">Votar por</option>
            <option value="candidato1"></option>
            <option value="candidato2"></option>
        </select>
        <button>enviar</button> 

      </form>
{% endblock %}