proyectonube2JOHN/Votaciones/Proyecto_nube/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
]

proyectonube2JOHN/Votaciones/app/urls.py
	
from django.urls import path 
from . import views 
 
app_name = 'app' 
urlpatterns = [
    path('index', views.index, name='index'),

    path('login/', views.login_view, name='login'),
    path('entrar/', views.entrar, name='entrar'),
    path('decano/', views.decano_view, name='decano'),
    path('estudiante/', views.estudiante_view, name='estudiante'),

    path('crearEstudiante/', views.crearEstudiante_view, name='crearEstudiante'),
    path('crearEstudiante_crear/', views.form_crearEstudiante_view, name='form_crearEstudiante_view'),
    path('crearEstudiante_post/', views.crearEstudiante_post, name='crearEstudiante_post'),
    path('listadoEstudiantes/', views.listadoEstudiantes_view, name='listadoEstudiantes'),
    
    
    path('crearVotacion_crear/', views.form_crearVotacion_view, name='form_crearVotacion_view'),
    path('crearVotacion_post/', views.crearVotacion_post, name='crearVotacion_post'),

    path('crearVotacion/', views.crearVotacion_view, name='crearVotacion'),
    path('listadoVotaciones/', views.listadoVotaciones_view, name='listadoVotaciones'),


    path('consultlaVotacionesRepre/', views.consultlaVotacionesRepre_view, name='consultlaVotacionesRepre'),


    path('postularCandidato/', views.postularCandidato_view, name='postularCandidato'),
    path('postularCandidato_crear/', views.form_postularCandidato_view, name='form_postularCandidato_view'),



    path('consultarVotacionE/', views.consultarVotacionE_view, name='consultarVotacionE'),
    path('votar_repre_fa/', views.votar_repre_fa_view, name='votar_repre_fa'),
    path('votar_repre_se/', views.votar_repre_se_view, name='votar_repre_se'),
    path('listadodevotaciones/', views.listadodevotaciones_view, name='listadodevotaciones'),
    path('consultarvotacion/', views.consultarvotacion_view, name='consultarvotacion'),
    path('postularse/', views.postularse_view, name='postularse'),
    path('consultavoto/', views.consultavoto_view, name='consultavoto'),
]

proyectonube2JOHN/Votaciones/app/templates/app/consultarVotacionE.html
{% extends "app/base3.html" %}
{% load static %}

{% block pestaña %}
<title>Decano: Consulta Votacion Estudiante</title>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'app/css/consultarVotacionE.css' %}">
{% endblock %}

{% block titulo %}
<i><a href="{% url 'app:login' %}"><img id="logout" src="{% static 'app/img/logout.jpg' %}" alt="logo" class="logout"></a></a></i>

<img id="logo" src="{% static 'app/img/logos.png' %}" alt="logo" class="logosantoto"></a>
{% endblock %}

{% block menu %}       
<nav class="menu">
    <ul>
        <h2>Menu</h2>
        <br>
        <li><a href="{% url 'app:crearEstudiante' %}">Crear Estudiante</a></li>
        <li><a href="{% url 'app:listadoEstudiantes' %}">Lista de Estudiantes</a></li>
        <li><a href="{% url 'app:crearVotacion' %}">Creacion Votacion</a></li>
        <li><a href="{% url 'app:listadoVotaciones' %}">Listado De Votacion</a></li>
        <li><a href="{% url 'app:decano' %}">Volver a Menu Decano</a></li>
    </ul>
</nav>
{% endblock %}

{% block contenido %}
<div class="datosdelestudiante">
    <form action="" >
        <div class="titulo1">
            <h2>Consultar votación repre semestre</h2>
        </div>
        {% for e in Votacion %}
        <div class="formulario1">  
            
          <div class="flex">
              <label for="">Nombre Votacion</label>
              <label for="">{{e.nombre}}</label>
              <!-- <input type="text" > -->
          </div>
          
          <div class="flex">
              <label for="">Fecha de Inicio</label>
              <label for="">{{e.fechaInicio}}</label>
              <!-- <input type="text"  > -->
          </div>
          <div class="flex">
              <label for="">Fecha De Finalizacion</label>
              <label for="">{{e.fechaFinal}}</label>
              <!-- <input type="text" > -->
          </div>

          <div class="flex">
              <label for="">Ciclo</label>
              <label for="">__ </label>
              <!-- <input type="text" >  -->
          </div>

          <div class="flex">
              <label for="">Estado Actual De La Votacion</label>
              <label for=""> __</label>
              <!-- <input type="text" > -->
          </div>
          <div class="flex">
              <label for="">Total De Estudiantes Habilitados Para Votar</label>
              <label for="">____</label>
              <!-- <input type="text" > -->
          </div>
          <div class="flex">
              <label for="">Estudiantes Que Han Votado</label>
              <label for="">____</label>
              <!-- <input type="text" > -->
          </div>
          <div class="flex">
              <label for="">Porcentaje De Votacion</label>
              <label for="">______</label>
              <!-- <input type="text" > -->
          </div>
        </div>
        {% endfor %}

        <div class="titulo2">
            <h3>Datos estudiantes</h3>
        </div>                      
      <table class="tabla1">
          <tr>
              <th>Nombre y Apellido</th>
              <th>N° de Votos</th>
              <th>Semestre</th>
          </tr>
          <tr>
              <td>candidato 1</td>
              <td>x</td>
              <td>x</td>
          </tr>
      </table>
      <div class="titulo2">
        <h3>Crear Estudiante</h3>
    </div>

      <div class="botones">
          <a href="{% url 'app:postularCandidato' %}" class="boton">Agregar Candidato</a>
     </div>            
    </form></div>
{% endblock %} 

proyectonube2JOHN/Votaciones/app/templates/app/consultarvotacion.html
{% extends "app/base3.html" %}
{% load static %}

{% block pestaña %}
<title>Estudiante: Consulta Votacion De Semestre</title>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'app/css/consultarvotacion.css' %}">
{% endblock %}

{% block titulo %}
<i><a href="{% url 'app:login' %}"><img id="logout" src="{% static 'app/img/logout.jpg' %}" alt="logo" class="logout"></a></a></i>

<img id="logo" src="{% static 'app/img/logos.png' %}" alt="logo" class="logosantoto"></a>

{% endblock %}


{% block menu %}     
<nav class="menu">
    <h1>Menu</h1>
    <ul> 
        <li><a href="{% url 'app:votar_repre_fa' %}">Votar por representante de facultad </a></li>
        <li><a href="{% url 'app:votar_repre_se' %}">Votar por representante de semestre</a></li>
        <li><a href="{% url 'app:listadodevotaciones' %}">Listado de votaciones</a></li>
        <li><a href="{% url 'app:estudiante' %}">Volver Menu Estudiante</a></li>
      </ul>
  </nav>
{% endblock %}

{% block contenido %}
<label value="represemestre" ></label>

            <br>
            <label>Fecha de inicio:</label>

            <br>
            <label>Fecha de finalizacion:</label>

            <br>
            <label>Ciclo:</label>

            <h2>Candidatos</h2>
            <table>
                <tr>
                    <td><strong>Nombres y apellidos</strong></td>
                    
                    <td><strong>N° de votos</strong></td>
                </tr>

                <tr>
                    <td>Pepito Pinilla Ramires</td>
                    <td>Aun no Disponible</td>
                </tr>

                <tr>
                    <td>Juana Marillo Robledo</td>
                    <td>Aun no Disponible</td>
                </tr>
                <br>
            </table>
            <a class="postularse" href="{% url 'app:postularse' %}">postularse</a> 
            <a class="consultar" href="{% url 'app:consultavoto' %}">consultar mi voto</a>
{% endblock %}

proyectonube2JOHN/Votaciones/app/templates/app/consultavoto.html
{% extends "app/base3.html" %}
{% load static %}

{% block pestaña %}
<title>Estudiante: Consulta Mi Voto</title>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'app/css/consultavoto.css' %}">
{% endblock %}

{% block titulo %}
<i><a href="{% url 'app:login' %}"><img id="logout" src="{% static 'app/img/logout.jpg' %}" alt="logo" class="logout"></a></a></i>

<img id="logo" src="{% static 'app/img/logos.png' %}" alt="logo" class="logosantoto"></a>

{% endblock %}


{% block menu %}     
<nav class="menu">
    <h1>Menu</h1>
    <ul> 
        <li><a href="{% url 'app:votar_repre_fa' %}">Votar por representante de facultad </a></li>
        <li><a href="{% url 'app:votar_repre_se' %}">Votar por representante de semestre</a></li>
        <li><a href="{% url 'app:listadodevotaciones' %}">Listado de votaciones</a></li>
        <li><a href="{% url 'app:estudiante' %}">Volver Menu Estudiante</a></li>
      </ul>
  </nav>
{% endblock %}

{% block contenido %}
<label>nombre de votacion</label>

            <br>
            <label>Fecha de inicio</label>

            <br>
            <label>Fecha de finalizacion</label>

            <br>
            <label>Ciclo</label>

            <br>
            <label>Tipo de votacion</label>

            <h1>Candidatos</h1>
            <table>
                <tr>
                    <td><strong>Nombres y apellidos</strong></td>
                    <td><strong>votó por</strong></td>
                </tr>

                <tr>
                    <td>Pepito Pinilla Ramires</td>
                    <td>X</td>
                </tr>

                <tr>
                    <td>Juana Marillo Robledo</td>
                    <td>    </td>
                </tr>
                <br>
            </table>
{% endblock %}

proyectonube2JOHN/Votaciones/app/templates/app/consultlaVotacionesRepre.html
{% extends "app/base3.html" %}
{% load static %}

{% block pestaña %}
<title>Decano: Consulta Votacion Repre</title>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'app/css/consultarVotacionesRepre.css' %}">
{% endblock %}

{% block titulo %}
<i><a href="{% url 'app:login' %}"><img id="logout" src="{% static 'app/img/logout.jpg' %}" alt="logo" class="logout"></a></a></i>

<img id="logo" src="{% static 'app/img/logos.png' %}" alt="logo" class="logosantoto"></a>
{% endblock %}

{% block menu %}       
<nav class="menu">
    <ul>
        <h2>Menu</h2>
        <br>
        <li><a href="{% url 'app:crearEstudiante' %}">Crear Estudiante</a></li>
        <li><a href="{% url 'app:listadoEstudiantes' %}">Lista de Estudiantes</a></li>
        <li><a href="{% url 'app:crearVotacion' %}">Creacion Votacion</a></li>
        <li><a href="{% url 'app:listadoVotaciones' %}">Listado De Votacion</a></li>
        <li><a href="{% url 'app:decano' %}">Volver a Menu Decano</a></li>
    </ul>
</nav>
{% endblock %}

{% block contenido %}
<div class="datosdelestudiante">
    <form action="" >
        <div class="titulo1">
            <h2>Consultar votación repre de facultad</h2>
        </div>
        {% for e in Votacion %}
        <div class="formulario1">  
            
          <div class="flex">
              <label for="">Nombre Votacion</label>
              <label for="">{{e.nombre}}</label>
              <!-- <input type="text" > -->
          </div>
          
          <div class="flex">
              <label for="">Fecha de Inicio</label>
              <label for="">{{e.fechaInicio}}</label>
              <!-- <input type="text"  > -->
          </div>
          <div class="flex">
              <label for="">Fecha De Finalizacion</label>
              <label for="">{{e.fechaFinal}}</label>
              <!-- <input type="text" > -->
          </div>

          <div class="flex">
              <label for="">Ciclo</label>
              <label for="">__ </label>
              <!-- <input type="text" >  -->
          </div>

          <div class="flex">
              <label for="">Estado Actual De La Votacion</label>
              <label for=""> __</label>
              <!-- <input type="text" > -->
          </div>
          <div class="flex">
              <label for="">Total De Estudiantes Habilitados Para Votar</label>
              <label for="">____</label>
              <!-- <input type="text" > -->
          </div>
          <div class="flex">
              <label for="">Estudiantes Que Han Votado</label>
              <label for="">____</label>
              <!-- <input type="text" > -->
          </div>
          <div class="flex">
              <label for="">Porcentaje De Votacion</label>
              <label for="">______</label>
              <!-- <input type="text" > -->
          </div>
        </div>
        {% endfor %}

        <div class="titulo2">
            <h3>Datos estudiantes</h3>
        </div>                      
      <table class="tabla1">
          <tr>
              <th>Nombre y Apellido</th>
              <th>N° de Votos</th>
              <th>Semestre</th>
          </tr>
          <tr>
              <td>candidato 1</td>
              <td>x</td>
              <td>x</td>
          </tr>
      </table>
      <div class="titulo2">
        <h3>Crear Estudiante</h3>
    </div>

      <div class="botones">
          <a href="{% url 'app:postularCandidato' %}" class="boton">Agregar Candidato</a>
     </div>            
    </form>
</div>
{% endblock %} 

proyectonube2JOHN/Votaciones/app/templates/app/crearEstudiante.html
{% extends "app/base3.html" %}
{% load static %}

{% block pestaña %}
<title>Decano: Crear Estudiante</title>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'app/css/estiloCrearEstudiante.css' %}">
{% endblock %}

{% block titulo %}
<i><a href="{% url 'app:login' %}"><img id="logout" src="{% static 'app/img/logout.jpg' %}" alt="logo" class="logout"></a></a></i>

<img id="logo" src="{% static 'app/img/logos.png' %}" alt="logo" class="logosantoto"></a>
{% endblock %}

{% block menu %}       
<nav class="menu">
    <ul>
        <h2>Menu</h2>
        <br>
        <li><a href="{% url 'app:crearEstudiante' %}">Crear Estudiante</a></li>
        <li><a href="{% url 'app:listadoEstudiantes' %}">Lista de Estudiantes</a></li>
        <li><a href="{% url 'app:crearVotacion' %}">Creacion Votacion</a></li>
        <li><a href="{% url 'app:listadoVotaciones' %}">Listado De Votacion</a></li>
        <li><a href="{% url 'app:decano' %}">Volver a Menu Decano</a></li>
    </ul>
</nav>
{% endblock %}

{% block contenido %}
<div class="datosdelestudiante">

    <form action="{% url 'app:crearEstudiante_post' %}" method="POST">
        {% csrf_token %}

        <div class="titulo1">
            <h1>Datos Del Estudiante</h1>
        </div>
        <div class="formulario1">
          <div class="flex">
              <label for="">Nombre</label>
              <input type="text" name="nombre" required>
          </div>
          <div class="flex">
              <label for="">Apellido</label>
              <input type="text" name='apellido' required>
          </div>
          <div class="flex">
              <label for="">Semestre</label>
              <input type="text" name="semestre" required>
          </div>

          <div class="flex">
              <label for="">Email</label>
              <input type="text" name="email" required> 
          </div>

          <div class="flex">
              <label for="">Documento</label>
              <input type="text" name="documento" required>
          </div>
          <br>
          <input class="enviar" type="submit"> 
        </div>                            
    </form>
</div> 
{% endblock %} 

proyectonube2JOHN/Votaciones/app/templates/app/estudiante.html
{% extends "app/base3.html" %}
{% load static %}

{% block pestaña %}
<title>Estudiante Menu</title>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'app/css/estudiantemenu.css' %}">
{% endblock %}

{% block titulo %}
<h1>Estudiante: (name)</h1>
<i><a href="{% url 'app:login' %}"><img id="logout" src="{% static 'app/img/logout.jpg' %}" alt="logo" class="logout"></a></a></i>
{% endblock %}


{% block menu %}     
<nav class="menu">
    <ul>
        <h2>Menu</h2>
        <br>
        <li><a href="{% url 'app:votar_repre_fa' %}">Votar por representante de facultad </a></li>
        <li><a href="{% url 'app:votar_repre_se' %}">Votar por representante de semestre</a></li>
        <li><a href="{% url 'app:listadodevotaciones' %}">Listado de votaciones</a></li>
    </ul>
</nav>
{% endblock %}

{% block contenido %}
<img id="logo" src="{% static 'app/img/logos.png' %}" alt="logo" class="logosantoto"></a>
{% endblock %}

proyectonube2JOHN/Votaciones/app/templates/app/listadoEstudiantes.html
{% extends "app/base3.html" %}
{% load static %}

{% block pestaña %}
<title>Decano: Listado De Estudiantes</title>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'app/css/estiloListadoEstudiantes.css' %}">
{% endblock %}

{% block titulo %}
<i><a href="{% url 'app:login' %}"><img id="logout" src="{% static 'app/img/logout.jpg' %}" alt="logo" class="logout"></a></a></i>

<img id="logo" src="{% static 'app/img/logos.png' %}" alt="logo" class="logosantoto"></a>
{% endblock %}

{% block menu %}       
<nav class="menu">
    <ul>
        <h2>Menu</h2>
        <br>
        <li><a href="{% url 'app:crearEstudiante' %}">Crear Estudiante</a></li>
        <li><a href="{% url 'app:listadoEstudiantes' %}">Lista de Estudiantes</a></li>
        <li><a href="{% url 'app:crearVotacion' %}">Creacion Votacion</a></li>
        <li><a href="{% url 'app:listadoVotaciones' %}">Listado De Votacion</a></li>
        <li><a href="{% url 'app:decano' %}">Volver a Menu Decano</a></li>
    </ul>
</nav>
{% endblock %}

{% block contenido %}
<div class="titulo1">
    <h1>Listado De Estudiantes</h1>              
</div>
<div>
    <table class="tabla1">
        <tr>
            <th>Nombre</th>
            <th>Apellido</th>
            <th>Email</th>
            <th>Documento</th>
        </tr>
        
        {% for e in lista %}
        <tr>
            <td>{{e.user.first_name}} </td>
            <td>{{e.user.last_name}} </td>
            <td>{{e.user.email}} </td>
            <td>{{e.documento}} </td>
          </tr>
        {% endfor %}

    </table>
</div>
{% endblock %} 

proyectonube2JOHN/Votaciones/app/templates/app/listadoVotaciones.html
{% extends "app/base3.html" %}
{% load static %}

{% block pestaña %}
<title>Decano: Listado De Votos</title>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'app/css/listadoVotaciones.css' %}">
{% endblock %}

{% block titulo %}
<i><a href="{% url 'app:login' %}"><img id="logout" src="{% static 'app/img/logout.jpg' %}" alt="logo" class="logout"></a></a></i>

<img id="logo" src="{% static 'app/img/logos.png' %}" alt="logo" class="logosantoto"></a>
{% endblock %}

{% block menu %}       
<nav class="menu">
    <ul>
        <h2>Menu</h2>
        <br>
        <li><a href="{% url 'app:crearEstudiante' %}">Crear Estudiante</a></li>
        <li><a href="{% url 'app:listadoEstudiantes' %}">Lista de Estudiantes</a></li>
        <li><a href="{% url 'app:crearVotacion' %}">Creacion Votacion</a></li>
        <li><a href="{% url 'app:listadoVotaciones' %}">Listado De Votacion</a></li>
        <li><a href="{% url 'app:decano' %}">Volver a Menu Decano</a></li>
    </ul>
</nav>
{% endblock %}

{% block contenido %}
<div class="titulo1">
    <h1>Listado de Votacion</h1>
</div>
  <table class="tabla1">
      <tr>
          <th>Nombre De Votacion</th>
          <th>Ciclo</th>
          <th>Fecha De Inicio</th>
          <th>Fecha De Finalizacion</th>
          <th>Tipo De Votacion</th>
          <th>Estado De Votacion</th>
      </tr>

      {% for e in Votacion %}
      <tr>
          <td class="consultaVoto"><li><a href="{% url 'app:consultlaVotacionesRepre' %}"> Estudiante 1</a></li></td>

          <td></td>
          <td></td>
          <td></td>
          <td>Facultad</td>
          <td><div class="flex">
              <br>    
            <label for="">Elige el estado de Votacion</label>
            <select class="opciones" required>
                <option value="">Tipo</option>
                <option value="1">Activo</option>
                <option value="1">Inactivo</option>
                <option value="3">Finalizar</option>
            </select>
        </div></td>
      </tr>

      <tr>
          <td class="consultaVoto"><li><a href="{% url 'app:consultarVotacionE' %}">{{e.nombre}}</a></li></td>
          <td></td>
          <td>{{e.fechaInicio}}</td>
          
          <td>{{e.fechaFinal}}</td>
          <td>{{e.tipo_id}}</td>

          <td><div class="flex">
              <br>
            <label for="">Elige el estado de Votacion</label>
            <select class="opciones" required>
                <option value="">Tipo</option>
                <option value="1">Activo</option>
                <option value="1">Inactivo</option>
                <option value="3">Finalizar</option>
            </select>
        </div></td>
      </tr>
      {% endfor %}
  </table>
{% endblock %} 

proyectonube2JOHN/Votaciones/app/templates/app/login.html
{% extends "app/base2.html" %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'app/css/estiloLogin.css' %}">
{% endblock %}


{% block login %}
<div class="login">
    <form action="{% url 'app:entrar' %}" method="POST" >
      {% csrf_token %}
      <!-- nombre de usuario -->
      <label class="nombre" for="username">Email</label>
      <br>
      <input name='username' class="caja" type="text" placeholder="Digite Email" required/>
      <br>
      <!-- contraseña -->
      <label class="nombre" for="password">Contraseña(Documento)</label>
      <br>
      <input name="password"  class="caja" type="password" placeholder="Contraseña" required/>
        <div class="botones">
            <button type="submit">Ingresar</button>
            <a href="{% url 'app:decano' %}" class="boton" >Decano</a>
            <a href="{% url 'app:estudiante' %}" class="boton">Estudiante</a>
            
       </div> 
       
    </form>
  </div>
{% endblock %}

proyectonube2JOHN/Votaciones/app/templates/app/postularCandidato.html
{% extends "app/base3.html" %}
{% load static %}

{% block pestaña %}
<title>Decano: Postular Candidato</title>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'app/css/postularCandidato.css' %}">
{% endblock %}

{% block titulo %}
<i><a href="{% url 'app:login' %}"><img id="logout" src="{% static 'app/img/logout.jpg' %}" alt="logo" class="logout"></a></a></i>

<img id="logo" src="{% static 'app/img/logos.png' %}" alt="logo" class="logosantoto"></a>
{% endblock %}

{% block menu %}       
<nav class="menu">
    <ul>
        <h2>Menu</h2>
        <br>
        <li><a href="{% url 'app:crearEstudiante' %}">Crear Estudiante</a></li>
        <li><a href="{% url 'app:listadoEstudiantes' %}">Lista de Estudiantes</a></li>
        <li><a href="{% url 'app:crearVotacion' %}">Creacion Votacion</a></li>
        <li><a href="{% url 'app:listadoVotaciones' %}">Listado De Votacion</a></li>
        <li><a href="{% url 'app:decano' %}">Volver a Menu Decano</a></li>
    </ul>
</nav>
{% endblock %}

{% block contenido %}
<div class="datosdelestudiante">
    <form action="{% url 'app:form_postularCandidato_view' %}" method="POST">

        {% csrf_token %}

        <div class="titulo1">
            <h1>Postulacio De Estudiante</h1>
        </div>
        <div class="formulario1">
            {% for v in Votacion %}
          <div class="flex">
              <label for="">Votacion</label>
              <label for="">{{v.nombre}}</label>
              <!-- <input type="text" > -->
          </div>
          {% endfor %}
          
          <div class="flex">
              <label for="">Estudiante</label>
              <input type="text" name="nombrePostular" >
          </div>
          

        </div>
      <div class="botones">
          <a href="{% url 'app:decano' %}" class="boton">Agregar Candidato</a>
     </div>            
    </form>
</div>
{% endblock %}

proyectonube2JOHN/Votaciones/app/templates/app/postularse.html
{% extends "app/base3.html" %}
{% load static %}

{% block pestaña %}
<title>Estudiante: Postularse</title>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'app/css/postularse.css' %}">
{% endblock %}

{% block titulo %}
<i><a href="{% url 'app:login' %}"><img id="logout" src="{% static 'app/img/logout.jpg' %}" alt="logo" class="logout"></a></a></i>

<img id="logo" src="{% static 'app/img/logos.png' %}" alt="logo" class="logosantoto"></a>

{% endblock %}


{% block menu %}     
<nav class="menu">
    <h1>Menu</h1>
    <ul> 
      <li><a href="{% url 'app:votar_repre_fa' %}">Votar por representante de facultad </a></li>
      <li><a href="{% url 'app:votar_repre_se' %}">Votar por representante de semestre</a></li>
      <li><a href="{% url 'app:listadodevotaciones' %}">Listado de votaciones</a></li>
      <li><a href="{% url 'app:estudiante' %}">Volver Menu Estudiante</a></li>
    </ul>
  </nav>
{% endblock %}

{% block contenido %}
<table>
    <h2>Postulaciones</h1>
    <tr>
        <td><strong>Propuestas</strong></td>
        <td><strong>Votacion</strong></td>
    </tr>
    <tr>
        <td><input type="text"></td>
        <td><select name="cars" id="cars">
                <optgroup label="tipo">
                    <option value="Semestre">Semestre</option>
                    <option value="Facultad">Facultad</option>
            </select></td>
    </tr>
</table>
<button class="enviar">enviar</button>
</div>
{% endblock %}

proyectonube2JOHN/Votaciones/app/templates/app/votar_repre_fa.html
{% extends "app/base3.html" %}
{% load static %}

{% block pestaña %}
<title>Estudiante: Votar por representante de facultad</title>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'app/css/votar_repre_fa.css' %}">
{% endblock %}

{% block titulo %}
<i><a href="{% url 'app:login' %}"><img id="logout" src="{% static 'app/img/logout.jpg' %}" alt="logo" class="logout"></a></a></i>

<img id="logo" src="{% static 'app/img/logos.png' %}" alt="logo" class="logosantoto"></a>

{% endblock %}


{% block menu %}     
<nav class="menu">
    <h1>Menu</h1>
    <ul> 
      <li><a href="{% url 'app:votar_repre_fa' %}">Votar por representante de facultad </a></li>
      <li><a href="{% url 'app:votar_repre_se' %}">Votar por representante de semestre</a></li>
      <li><a href="{% url 'app:listadodevotaciones' %}">Listado de votaciones</a></li>
      <li><a href="{% url 'app:estudiante' %}">Volver Menu Estudiante</a></li>
    </ul>
  </nav>
{% endblock %}

{% block contenido %}
<h2>Representante de Facultad</h2>
      <form>
        <label>Nombre de votacion: </label>

        <br>
        <label>Fecha de inicio: </label>

        <br>
        <label>Fecha de finalizacion: </label>

        <h3>Estudiantes postulados</h3>
        <table>
          <tr>
            <td><strong>Nombres y apellidos</strong></td>
            <td><strong>Propuestas</strong></td>
          </tr>

          <tr>
            <td id="candidato1">Pepito Pinilla Ramires</td>
            <td >Hacer una psicina</td>
          </tr>

          <tr>
            <td id="candidato2">Juana Marillo Robledo</td>
            <td>no mas clases</td>
          </tr>
          <br>
        </table>
        <select name="candidatos" id="candidatos">
          <optgroup label="votar">
            <option value="votar por">votar por</option>
            <option value="candidato1"></option>
            <option value="candidato2"></option>
        </select>
        <button>enviar</button>

      </form>
{% endblock %}